#!/usr/bin/env bash

function bootstrap {
  local shome="$(unset CDPATH; cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  local url_elixir='https://github.com/elixir-lang/elixir/releases/download/v1.0.5/Precompiled.zip'

  local tmp_elixir="$(mktemp -t XXXXXX)"
  trap "$(printf "rm -f '%q'" "$tmp_elixir")" EXIT
  curl -L -o "$tmp_elixir" "$url_elixir"
  (cd "$shome/install"; unzip "$tmp_elixir")

  (set +f; rm -f "$shome/install/bin"/*.bat)
}

bootstrap
