#!/usr/bin/env bash

function bootstrap {
  local shome="${_elixir_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  local url_elixir='https://github.com/elixir-lang/elixir/releases/download/v1.3.2/Precompiled.zip'

  local tmp_elixir="$(mktemp -t XXXXXX)"
  trap "$(printf "rm -f '%q'" "$tmp_elixir")" EXIT
  curl -sS -L -o "$tmp_elixir" "$url_elixir"

  (cd "$shome/install"; unzip -o "$tmp_elixir")
  (set +f; rm -f "$shome/install/bin"/*.bat)

  mix local.hex --force
  mix local.rebar --force
}

bootstrap
