#!/usr/bin/env bash

function profile {
  local shome="${_elixir_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  PATH="$shome/bin:$shome/install/bin:$PATH"

  ELIXIR_VERSION='1.7.2'
}

profile
