#!/usr/bin/env bash

function version {
  local shome="${_elixir_home:-"$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"}"
  source "$shome/script/profile"

  local ver_elixir="$(elixir --version 2>/dev/null | awk '/^Elixir/ {print $2}' || true)"
  jq -n --arg elixir "$ver_elixir" '{elixir: $elixir}'
}

version "$@"
