#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_elixir="$(elixir --version 2>&- | awk '/^Elixir/ {print $2}' || true)"
  jq -n --arg elixir "$ver_elixir" '{elixir: $elixir}'
}

version "$@"
